version: "3.11"

x-service-volumes: &service-volumes
  - ./:/app/:rw,cached

services:
  website:
    image: storefront:latest
    command: python manage.py runserver 0.0.0.0:8000
    volumes: *service-volumes
    depends_on:
      - "db_migrate"
    ports: 
    - "8000:8000"

  db_migrate:
    image: storefront:latest
    command: python manage.py migrate
    volumes: *service-volumes

